const services=[
 ['01 · CONVERSATION','Tell Sebastian<br><em>anything.</em>','Speak naturally. Ask a question, explain a problem, make a plan or simply say, “Sebastian, help me with this.”','“I have a wedding next Saturday. What should I wear?”'],
 ['02 · PRODUCTIVITY','Your day,<br><em>perfectly orchestrated.</em>','Tasks, reminders, priorities and schedules — organised around what matters to you.','“Remind me to buy groceries tomorrow at 5 PM.”'],
 ['03 · TRAVEL','Travel without<br><em>the planning.</em>','Bring weather, destinations, hotels, flights, activities and itineraries together in one conversation.','“I’m travelling to Cape Town next Friday. Organise everything.”'],
 ['04 · FOOD & RECIPES','Your private<br><em>chef.</em>','Create, modify, scale and narrate recipes around your ingredients and dietary preferences.','“I have chicken, rice and tomatoes. What can I make?”'],
 ['05 · STYLE','Always<br><em>appropriately dressed.</em>','Consider your style, the occasion, weather and preferences to build a complete look.','“I have a black-and-gold soirée this Saturday.”'],
 ['06 · DISCOVERY','Discover what’s<br><em>around you.</em>','Find restaurants, cafés, events and activities using location, time, budget and preferences.','“I have two free hours. Find something interesting nearby.”'],
 ['07 · INTELLIGENCE','Know what<br><em>matters.</em>','Search trusted sources and turn current information into concise, sourced intelligence.','“Give me today’s most important headlines.”'],
 ['08 · WELLNESS','Take better care<br><em>of your day.</em>','Gentle reminders to hydrate, stretch, move, rest and follow simple fitness routines.','“Give me a five-minute desk routine.”'],
 ['09 · SAFETY','When you need<br><em>a way out.</em>','With permission, identify nearby public or emergency locations and route information where supported.','“I don’t feel safe. Help me find somewhere public.”'],
 ['10 · PERSONALISATION','Sebastian remembers<br><em>what matters.</em>','With your permission, remember useful preferences while keeping you in control of your memory.','“Remember that I prefer quiet cafés and morning meetings.”']
];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const navbar=$('#navbar');
addEventListener('scroll',()=>navbar.classList.toggle('scrolled',scrollY>40),{passive:true});
$('#menuToggle').addEventListener('click',()=>{const n=$('#navLinks');n.classList.toggle('open');$('#menuToggle').setAttribute('aria-expanded',n.classList.contains('open'))});
$$('#navLinks a').forEach(a=>a.addEventListener('click',()=>$('#navLinks').classList.remove('open')));
const fill=$('#progressFill'),eb=$('#serviceEyebrow'),title=$('#serviceTitle'),text=$('#serviceText'),ex=$('#serviceExample'),count=$('#serviceCount');
function updateStory(){const sec=$('.tray-story');const rect=sec.getBoundingClientRect();const total=sec.offsetHeight-innerHeight;const progress=Math.max(0,Math.min(1,-rect.top/total));const idx=Math.min(services.length-1,Math.floor(progress*services.length));const s=services[idx];fill.style.width=((idx+1)/services.length*100)+'%';if(eb.dataset.i!==String(idx)){eb.dataset.i=idx;eb.animate([{opacity:.25,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:450,easing:'ease-out'});title.animate([{opacity:.25,transform:'translateY(14px)'},{opacity:1,transform:'none'}],{duration:550,easing:'ease-out'});text.animate([{opacity:.25},{opacity:1}],{duration:600});ex.animate([{opacity:0},{opacity:1}],{duration:700})}eb.innerHTML=s[0];title.innerHTML=s[1];text.textContent=s[2];ex.textContent=s[3];count.textContent=`${String(idx+1).padStart(2,'0')} / ${services.length}`}
addEventListener('scroll',updateStory,{passive:true});addEventListener('resize',updateStory);updateStory();

const modal=$('#modal');const authInputs=$$('#authForm input');authInputs.forEach(input=>{input.style.fontSize='16px'});
const supabaseClient=window.supabaseClient||((window.supabase&&window.SUPABASE_URL&&window.SUPABASE_ANON_KEY)?window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY):null);
function openModal(type){modal.classList.add('open');modal.setAttribute('aria-hidden','false');
    const signup=type==='signup';$('#modalEyebrow').textContent=signup?'WELCOME · JOIN SEBASTIAN':'WELCOME BACK';$('#modalTitle').textContent=signup?'Create your account.':'Welcome back.';$('#modalText').textContent=signup?'Your personal butler experience begins here.':'Continue to your Sebastian experience.';$('#authName').parentElement.style.display=signup?'block':'none';$('#authSubmit').innerHTML=signup?'Create account <span>→</span>':'Login <span>→</span>';setTimeout(()=>modal.querySelector('input:not([style*="display: none"])')?.focus(),100)}
$$('[data-modal]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();openModal(a.dataset.modal)}));$$('[data-close]').forEach(x=>x.addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}));addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('open')});
$('#authForm').addEventListener('submit',e=>{e.preventDefault();modal.classList.remove('open');showToast('Demo form submitted — connect your authentication provider to enable accounts.')});
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3600)}
$('#voiceDemo').addEventListener('click',()=>{const audio = new Audio('assets/Sebastian-voice.mpeg');audio.preload='auto';audio.volume=1;audio.play().then(()=>showToast('Sebastian is speaking.')).catch(()=>{if(!('speechSynthesis'in window)){showToast('Speech synthesis is not available in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance('Good to see you. I’m Sebastian. How may I assist you?');const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>/Daniel|David|Mark|Alex|Google UK English Male|Microsoft David|Microsoft Mark/i.test(v.name)&&/^en/i.test(v.lang))||voices.find(v=>/^en/i.test(v.lang))||null;u.rate=.93;u.pitch=.82;speechSynthesis.speak(u);showToast('Sebastian is speaking.');});});
